# Generated by Django 3.2.9 on 2021-12-13 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='favorite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='share_user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, related_name='share_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
