# Generated by Django 3.2.9 on 2021-12-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0004_alter_simulation_share_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='share_user',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_fav', to='sim_manager.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_fav', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_share', to='sim_manager.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
