# Generated by Django 3.2.1 on 2021-12-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(max_length=2)),
                ('batiment', models.CharField(max_length=3)),
                ('salle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('titre', models.TextField(max_length=100)),
                ('semestre', models.CharField(max_length=1)),
                ('annee', models.IntegerField()),
                ('mots_cles', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INE', models.IntegerField()),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('niveau', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.IntegerField()),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes', to='gestion_cours.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_groupe', models.IntegerField()),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cours.intervenant')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.cours')),
            ],
        ),
        migrations.CreateModel(
            name='TD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_groupe', models.IntegerField()),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cours.intervenant')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_inscrit', to='gestion_cours.etudiant')),
                ('td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.td')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cours.tp')),
            ],
        ),
        migrations.AddConstraint(
            model_name='etudiant',
            constraint=models.UniqueConstraint(fields=('INE',), name="Contrainte d'unicité de l'INE"),
        ),
        migrations.AddField(
            model_name='cours',
            name='etudiant',
            field=models.ManyToManyField(through='gestion_cours.Inscrire', to='gestion_cours.Etudiant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='intervenants',
            field=models.ManyToManyField(related_name='intervient_dans', to='gestion_cours.Intervenant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='est_responsable', to='gestion_cours.intervenant'),
        ),
        migrations.AddConstraint(
            model_name='bureau',
            constraint=models.UniqueConstraint(fields=('centre', 'batiment', 'salle'), name="Contrainte d'unicité du bureau"),
        ),
        migrations.AddConstraint(
            model_name='intervenant',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom'), name="Contrainte d'unicité de la personne"),
        ),
        migrations.AddConstraint(
            model_name='inscrire',
            constraint=models.UniqueConstraint(fields=('cours', 'etudiant'), name='Etudiant déjà inscrit'),
        ),
    ]
